output "domain_account_password" {
    sensitive = true
    description = "Password for the domain admin account generated by Terraform"
    value = random_password.local_administrator_password.result
}